import { parseContractManifest, type ContractManifest } from './manifest'

function literal(value: unknown) {
  return JSON.stringify(value, null, 2)
}

/** Generates a dependency-free TypeScript catalog from a validated JSON manifest. */
export function generateContractModule(input: ContractManifest | unknown): string {
  const manifest = parseContractManifest(input)
  const actions = manifest.contracts.map(contract => contract.action)
  const contractIds = manifest.contracts.map(contract => contract.contractId)
  const fixtures = Object.fromEntries(
    manifest.contracts
      .filter(contract => contract.examples)
      .map(contract => [contract.action, contract.examples]),
  )
  return `// Generated by Causync. Do not edit by hand.\n\n` +
    `export const causyncManifest = ${literal(manifest)} as const\n\n` +
    `export const causyncActions = ${literal(actions)} as const\n` +
    `export type CausyncAction = typeof causyncActions[number]\n\n` +
    `export const causyncContractIds = ${literal(contractIds)} as const\n` +
    `export type CausyncContractId = typeof causyncContractIds[number]\n\n` +
    `export type CausyncCommandEnvelope<TAction extends CausyncAction, TInput> = {\n` +
    `  action: TAction\n  contractId: CausyncContractId\n  mutationId: string\n  input: TInput\n}\n\n` +
    `export type CausyncReceiptEnvelope<TReceipt> = {\n` +
    `  mutationId: string\n  contractId: CausyncContractId\n  receipt: TReceipt\n}\n\n` +
    `export const causyncFixtures = ${literal(fixtures)} as const\n`
}
